// react/nextjs components
import type { Metadata } from "next";

// styling
import "@/styles/globals.css";
import { Inter } from "next/font/google";

// custom components
import Header from "@/components/navLayout/header/Header";
import HeaderMobile from "@/components/navLayout/header/HeaderMobile";
import Sidebar from "@/components/navLayout/sideMenu/Sidebar";
import PageWrapper from "@/components/PageWrapper";
import MarginWidthWrapper from "@/components/MarginWidthWrapper";
import DropDownModal from "@/components/DropDownModal";
import Alert from "@/components/Alert";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-white ${inter.className}`}>
        <div className="relative flex">
          <Sidebar />
          <main className="flex-1">
            <MarginWidthWrapper>
              <Header />
              <HeaderMobile />
              <PageWrapper>
                {children}
              </PageWrapper>
            </MarginWidthWrapper>
          </main>
          <DropDownModal />
          <Alert />
        </div>
      </body>
    </html>
  );
}
