// react/nextjs components
import type { Metadata } from "next";

// styling
import "@/styles/globals.css";
import { Inter } from "next/font/google";

// custom components
import Header from "@/components/Header";
import HeaderMobile from "@/components/HeaderMobile";
import Sidebar from "@/components/sideMenu/Sidebar";
import PageWrapper from "@/components/PageWrapper";
import MarginWidthWrapper from "@/components/MarginWidthWrapper";
import Alert from "@/components/Alert";
import { AuthProvider } from "@/components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TriaList",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-slate-50 ${inter.className}`}>
        <div className="flex">
          <Sidebar />
          <main className="flex-1">
            <AuthProvider>
              <MarginWidthWrapper>
                <Header />
                <HeaderMobile />
                <PageWrapper>{children}</PageWrapper>
              </MarginWidthWrapper>
            </AuthProvider>
          </main>
          <Alert />
        </div>
      </body>
    </html>
  );
}
