export const timeZoneToCountry: { [key: string]: string }= {
    'Africa/Cairo': 'Egypt',
    'Africa/Johannesburg': 'South Africa',
    'Africa/Lagos': 'Nigeria',
    'America/New_York': 'United States',
    'America/Los_Angeles': 'United States',
    'America/Chicago': 'United States',
    'America/Toronto': 'Canada',
    'America/Mexico_City': 'Mexico',
    'Asia/Tokyo': 'Japan',
    'Asia/Shanghai': 'China',
    'Asia/Kolkata': 'India',
    'Asia/Dubai': 'United Arab Emirates',
    'Asia/Singapore': 'Singapore',
    'Australia/Sydney': 'Australia',
    'Europe/London': 'United Kingdom',
    'Europe/Paris': 'France',
    'Europe/Berlin': 'Germany',
    'Europe/Moscow': 'Russia',
    'Europe/Rome': 'Italy',
    'Pacific/Auckland': 'New Zealand',
    'Pacific/Honolulu': 'United States (Hawaii)',
    'America/Sao_Paulo': 'Brazil',
    'America/Argentina/Buenos_Aires': 'Argentina',
    'Asia/Seoul': 'South Korea',
    'Asia/Hong_Kong': 'Hong Kong',
    'Asia/Bangkok': 'Thailand',
    'Asia/Jakarta': 'Indonesia',
    'Europe/Madrid': 'Spain',
    'Europe/Amsterdam': 'Netherlands',
    'Europe/Brussels': 'Belgium',
    'Europe/Zurich': 'Switzerland',
    'Europe/Vienna': 'Austria',
    'Europe/Stockholm': 'Sweden',
    'Africa/Nairobi': 'Kenya',
    'Africa/Addis_Ababa': 'Ethiopia',
    'America/Bogota': 'Colombia',
    'America/Lima': 'Peru',
    'America/Santiago': 'Chile',
    // Add more mappings as needed
  };